apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: timescaledb
  namespace: argocd
spec:
  project: default
  source:
    # 1. The URL to your git repository
    repoURL: https://github.com/syacef/Stryx.git
    # 2. The branch to track
    targetRevision: HEAD
    # 3. The path inside the repo where timescaledb-k3s.yaml lives
    path: k8s/timescaledb
  destination:
    # 4. Deploy to the same cluster ArgoCD is running on
    server: https://kubernetes.default.svc
    # 5. The namespace where TimescaleDB should actually run
    namespace: timescaledb
  # 6. Sync Policy: Automatically heal drift (if someone deletes a pod manually, Argo recreates it)
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true