apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: timescaledb-pvc
  namespace: timescaledb
spec:
  accessModes:
    - ReadWriteOnce
  # "local-path" is the default storage class in k3s
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi