# 1. Password Secret
apiVersion: v1
kind: Secret
metadata:
  name: timescaledb-secret
  namespace: timescaledb
type: Opaque
stringData:
  # CHANGE THIS PASSWORD for production!
  password: "supersecurepassword123"