apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingestion-service-ingress
  namespace: video-processing
spec:
  ingressClassName: traefik
  rules:
  - host: ingestion.localhost
    http:
      paths:
      - path: /streams
        pathType: Prefix
        backend:
          service:
            name: ingestion-service
            port:
              number: 8080
