apiVersion: v1
kind: Service
metadata:
  name: redisinsight-service
  namespace: video-processing
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 5540
  selector:
    app: redisinsight
