[project]
name = "model"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=4.5.0",
    "decord>=0.6.0",
    "torch>=2.9.1",
    "torchvision>=0.24.1",
]
