apiVersion: v1
kind: ConfigMap
metadata:
  name: svc-relay-config
  namespace: video-processing
data:
  LOG_LEVEL: "INFO"
  # Redis Settings
  REDIS_HOST: "redis.redis.svc.cluster.local"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  # RTSP Settings
  RTSP_PORT: "8554"
  DOMAIN: "relay.localhost"
  # API Settings
  API_PORT: "8000"
  API_HOST: "0.0.0.0"
