apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: svc-relay-tcp
  namespace: video-processing
spec:
  entryPoints:
    - rtsp
  routes:
  - match: HostSNI(`*`)
    services:
    - name: svc-relay
      port: 8554
