apiVersion: v1
kind: Service
metadata:
  name: svc-relay
  namespace: video-processing
spec:
  clusterIP: None
  type: ClusterIP
  selector:
    app: svc-relay
  ports:
  - name: http
    port: 8000
  - name: rtsp
    port: 8554
