apiVersion: v1
kind: Secret
metadata:
  name: video-processing-secret
  namespace: video-processing
type: Opaque
stringData:
  postgres-user: "postgres"
  postgres-password: "postgres"
  postgres-db: "safari"
  redis-password: ""
