apiVersion: v1
kind: ConfigMap
metadata:
  name: inference-service-config
  namespace: video-processing
data:
  # Redis Configuration
  REDIS_HOST: "redis.redis.svc.cluster.local"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  REDIS_QUEUE: "frame_queue"

  # Model Configuration (Inference Service)
  MODEL_TYPE: "dummy"
  BATCH_SIZE: "8"
  BATCH_TIMEOUT: "2.0"

  DB_HOST: "timescaledb.timescaledb.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "safari"
