apiVersion: v1
data:
  project: ZGVmYXVsdA==
  type: Z2l0
  url: aHR0cHM6Ly9naXRodWIuY29tL3N5YWNlZi9TdHJ5eA==
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  creationTimestamp: "2026-01-19T15:57:24Z"
  labels:
    argocd.argoproj.io/secret-type: repository
  name: repo-976075510
  namespace: argocd
type: Opaque
