apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: video-processing-base
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/syacef/Stryx.git
    targetRevision: HEAD
    path: k8s/apps/video-processing-base
  destination:
    server: https://kubernetes.default.svc
    namespace: video-processing
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: video-processing-ingestion
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/syacef/Stryx.git
    targetRevision: HEAD
    path: k8s/apps/ingestion-service
  destination:
    server: https://kubernetes.default.svc
    namespace: video-processing
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: video-processing-inference
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/syacef/Stryx.git
    targetRevision: HEAD
    path: k8s/apps/inference-service
  destination:
    server: https://kubernetes.default.svc
    namespace: video-processing
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
