apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stryx-ingress
  namespace: video-processing
spec:
  ingressClassName: traefik
  rules:
  - host: stryx.localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: port-front
            port:
              number: 80
